// portal-ui/src/app/components/edit-feature-field/edit-feature-field.component.ts
import { Component, OnInit, OnDestroy, OnChanges, Input, ViewChild, ElementRef } from '@angular/core';
import { createElement } from 'react';
import { render, unmountComponentAtNode } from 'react-dom';

import { EditedField, FieldType } from '../../services/crg/schema.models';
import { EditFeatureField } from '../EditFeatureField/EditFeatureField';
import { WfsFeature } from '../../services/geoserver/wfs.models';
import { CrgLayer } from '../../services/crg/projects.models';

@Component({
  selector: 'crg-edit-feature-field',
  template: '<div class="edit-feature-field" #react></div>',
  styleUrls: ['./edit-feature-field.component.scss']
})
export class EditFeatureFieldComponent implements OnInit, OnDestroy, OnChanges {
  @Input() type: FieldType;
  @Input() field: EditedField;
  @Input() feature: WfsFeature;
  @Input() isNew: boolean;
  @Input() isReadOnly: CrgLayer;
  @Input() layer?: CrgLayer;
  @ViewChild('react', { read: ElementRef, static: true }) ref: ElementRef;

  ngOnInit() {
    this.renderReactElement();
  }

  ngOnDestroy() {
    unmountComponentAtNode(this.ref.nativeElement);
  }

  ngOnChanges() {
    this.renderReactElement();
  }

  private renderReactElement() {
    const reactElement = createElement(EditFeatureField, {
      type: this.type,
      field: this.field,
      featureInfo: {
        feature: this.feature,
        isNew: this.isNew,
        layerName: this.layer ? this.layer.tableName : '',
        isReadOnly: Boolean(this.isReadOnly)
      }
    });

    render(reactElement, this.ref.nativeElement);
  }
}

// portal-ui/src/app/components/EditFeatureField/EditFeatureField.tsx
import React, { Component } from 'react';
import { cn } from '@bem-react/classname';

import { FieldType, EditedField } from '../../services/crg/schema.models';
import { WfsFeature } from '../../services/geoserver/wfs.models';

import { EditFeatureFieldField } from './Field/EditFeatureField-Field';
import { EditFeatureFieldLabel } from './Label/EditFeatureField-Label';

import '!style-loader!css-loader!sass-loader!./EditFeatureField.scss';

const cnEditFeatureField = cn('EditFeatureField');

export interface EditFeatureInfo {
  layerName: string;
  feature: WfsFeature;
  isReadOnly: boolean;
  isNew?: boolean;
}

interface EditFeatureFieldProps {
  type: FieldType;
  field: EditedField;
  featureInfo: EditFeatureInfo;
}

export class EditFeatureField extends Component<EditFeatureFieldProps> {
  render() {
    const { type, field, featureInfo } = this.props;

    return (
      <div className={cnEditFeatureField({ type: this.props.type })}>
        <EditFeatureFieldLabel>{field.property.title}</EditFeatureFieldLabel>
        <EditFeatureFieldField type={type} field={field} featureInfo={featureInfo} />
      </div>
    );
  }
}
