// portal-ui/src/app/components/data-import-tasks-list/DataImportTasksList.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import { observable, computed, action } from 'mobx';
import { cn } from '@bem-react/classname';


import {services} from '../../services/services';
import {ImportTaskProgress, ImportTaskShort, ImportTaskFull} from '../../services/geoserver/import/models';
import {NameHrefProjection} from '../../services/geoserver/projections';

const cnDataImportTasksList = cn('DataImportTasksList');

interface Task extends ImportTaskShort {
  layer?: NameHrefProjection;
}

interface DataImportTasksListProps {
  tasks: ImportTaskShort[];
  importState?: string;
}

@observer
export class DataImportTasksList extends React.Component<DataImportTasksListProps> {
  @observable
  private tasks: Task[] = [];

  @observable
  private progress?: ImportTaskProgress;

  private progressTimeout: number;

  constructor(props: DataImportTasksListProps) {
    super(props);

    this.setTasks(props.tasks);
  }

  componentDidMount () {
    this.updateTasks();
  }

  componentDidUpdate () {
    this.setTasks(this.props.tasks);

    if (['COMPLETE', 'ERROR'].includes(this.props.importState)) {
      this.setProgress();
      window.clearTimeout(this.progressTimeout);
    }
  }

  componentWillUnmount () {
    window.clearTimeout(this.progressTimeout);
  }

  render() {
    const { tasks } = this;

    return (
      <table className={cnDataImportTasksList()}>
        <tbody>
          {tasks.map(task => {
            const { layer } = task;
            const progress = task.state === 'RUNNING' && this.progress;

            return (
              <tr className={cnDataImportTasksList('Task', {error: this.isError(task)})} key={task.id}>
                <td className={cnDataImportTasksList('TaskName')}>
                  {layer ? layer.name : ''}
                </td>
                <td className={cnDataImportTasksList('TaskStatus')}>
                  {this.getDescription(task)}
                </td>
                <td className={cnDataImportTasksList('TaskProgress')}>
                  {progress ? progress.progress : '\u00A0'}
                  {progress && progress.total ? ` / ${progress.total}` : ''}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    );
  }

  @action
  private setTasks (tasks: Task[]) {
    tasks.forEach((task, i) => {
      const oldTask = this.tasks.find((t) => t.id === task.id);
      if (oldTask) {
        this.tasks[this.tasks.indexOf(oldTask)] = Object.assign(oldTask, task);
      } else {
        this.tasks.push(task);
      }
    });
  }

  private async updateTasks() {
    const tasks = await Promise.all(
      this.tasks.map(task => services.importService.getFullImportTask(task))
    );

    this.setTasks(tasks);

    this.checkProgress();
  }

  private async checkProgress () {
    const progress = await services.importService.getImportTaskProgress(this.tasks[0] as ImportTaskFull);

    if (progress.state === 'COMPLETE') {
      this.setProgress();
    } else {
      this.setProgress(progress);
    }

    if (!['COMPLETE', 'ERROR'].includes(this.props.importState)) {
      this.progressTimeout = window.setTimeout(() => {
        this.checkProgress();
      }, 300);
    }
  }

  @action
  setProgress (progress?: ImportTaskProgress) {
    this.progress = progress;
  }

  private isError(task: Task): boolean {
    return services.importService.isTaskError(task);
  }

  private getDescription(task: Task): string {
    const {state} = task;
    const {taskStatusesList} = services.importService;
    if (Object.keys(taskStatusesList).includes(state)) {
      return taskStatusesList[state];
    } else {
      return 'Неопределенный статус';
    }
  }
}

// portal-ui/src/app/components/data-import-tasks-list/data-import-tasks-list.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {ImportService} from '../../services/geoserver/import/import.service';
import {ImportTaskFull, ImportTaskProgress, ImportTaskShort} from '../../services/geoserver/import/models';

interface ImportTaskExtended extends ImportTaskFull {
  progressValue?: ImportTaskProgress;
}

type Task = ImportTaskExtended | ImportTaskShort;

interface TasksBuffer {
  [key: number]: ImportTaskExtended;
}

@Component({
  selector: 'crg-data-import-tasks-list',
  templateUrl: './data-import-tasks-list.component.html',
  styleUrls: ['./data-import-tasks-list.component.scss']
})
export class DataImportTasksListComponent implements OnInit {
  @Input() tasks: ImportTaskShort[];

  private FETCH_DELAY = 100;

  private currentTaskNum = -1;
  private tasksBuffer: TasksBuffer = {};
  private lastFetched = 0;

  get extendedTasks (): Task[] {
    return this.tasks.map(task => (this.tasksBuffer[task.id] ? this.tasksBuffer[task.id] : task));
  }

  constructor(private importService: ImportService) { }

  ngOnInit () {
    this.fetchNextTask();
  }

  isPending (task: Task): boolean {
    return this.importService.isTaskPending(task);
  }

  isError (task: Task): boolean {
    return this.importService.isTaskError(task);
  }

  getDescription(task: Task): string {
    const { state } = task;
    const { taskStatusesList } = this.importService;
    if (Object.keys(taskStatusesList).includes(state)) {
      return taskStatusesList[state];
    } else {
      return 'Неопределенный статус';
    }
  }

  private fetchNextTask (): void {
    if (!this.hasUncompletedTasks()) { return; }

    const now = new Date().getTime();
    if (now - this.lastFetched < this.FETCH_DELAY) {
      setTimeout(() => {
        this.fetchNextTask();
      }, this.FETCH_DELAY - now + this.lastFetched);
      return;
    }
    this.lastFetched = now;

    this.bumpCurrentTaskNum();

    const task = this.extendedTasks[this.currentTaskNum];

    if (this.isTaskCompleted(task)) {
      this.fetchNextTask();
      return;
    }

    if (!this.isTaskFull(task)) {
      this.fillTask(task);
      return;
    }

    this.updateTaskProgress(task as ImportTaskExtended);
  }

  private updateTaskProgress (task: ImportTaskExtended) {
    this.importService.getImportTaskProgress(task).subscribe(progress => {
      this.tasksBuffer[task.id].progressValue = progress;
      this.tasksBuffer[task.id].state = progress.state;
      this.fetchNextTask();
    });
  }

  private fillTask (task: Task): void {
    this.importService.getFullImportTask(task).subscribe(({ task }) => {
      this.tasksBuffer[task.id] = task;
      this.fetchNextTask();
    });
  }

  private bumpCurrentTaskNum (): void {
    this.currentTaskNum = this.currentTaskNum === this.tasks.length - 1 ?
                            0 :
                            this.currentTaskNum + 1;
  }

  private hasUncompletedTasks (): boolean {
    return this.extendedTasks.some(task => !this.isTaskCompleted(task));
  }

  private isTaskCompleted (task: Task) {
    return this.isTaskExtended(task) && !this.isPending(task);
  }

  private isTaskFull (task: Task): boolean {
    return task.hasOwnProperty('layer');
  }

  private isTaskExtended (task: Task): boolean {
    return task.hasOwnProperty('progressValue');
  }
}

<div class="data-import-tasks-list">
  <table class="data-import-tasks-list__table">
    <tr
        *ngFor="let task of extendedTasks"
        class="data-import-tasks-list__task"
        [ngClass]="{'data-import-tasks-list__task_error': isError(task)}">
      <td class="data-import-tasks-list__task-name">
        {{ task.layer?.name }}
      </td>
      <td class="data-import-tasks-list__task-status">
        {{ getDescription(task) }}
      </td>
      <td class="data-import-tasks-list__task-progress">
        {{ task.progressValue?.progress }}
        {{ task.progressValue?.total ? '/' : '' }}
        {{ task.progressValue?.total }}
      </td>
    </tr>
  </table>
</div>
